import type { NextPage } from "next";
import Head from "next/head";
import { Carousell } from "../components/Carousell";
import { ListSongs } from "../components/ListSongs";
import { Layout } from "../components/Layout";
import { wrapper } from "../store/store";
import { Playlist } from "../components/Playlist";
// import { setAuthState } from "../store/authSlice";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Java Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousell />
      <ListSongs />
      <Playlist />
    </Layout>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async ({}) => {
      console.log("State on server", store.getState());
      return {
        props: {
          authState: false,
        },
      };
    }
);

export default Home;
